// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.eduvision.eduvision.scan

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ScanApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/**
 * Result of looking at a full photo of a worksheet page.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PageDetection (
  /** Raw QR text, or null when no QR could be read. */
  val qrPayload: String? = null,
  /**
   * Centres of the ArUco markers id 0..3 (top-left, top-right,
   * bottom-right, bottom-left) in pixel coordinates of the photo as decoded
   * with its EXIF orientation applied: [x0, y0, x1, y1, x2, y2, x3, y3].
   * Both values of a marker that was not found are null.
   */
  val markerCorners: List<Double?>,
  /**
   * Ids (0..3) of the markers that were not found, so the UI can say which
   * corner is out of the frame.
   */
  val missingMarkerIds: List<Long>,
  /**
   * Variance of the Laplacian. Measured on the marker frame warped to
   * 200 DPI when all four markers were found, otherwise on the downscaled
   * photo. Higher is sharper.
   */
  val blurScore: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PageDetection {
      val qrPayload = pigeonVar_list[0] as String?
      val markerCorners = pigeonVar_list[1] as List<Double?>
      val missingMarkerIds = pigeonVar_list[2] as List<Long>
      val blurScore = pigeonVar_list[3] as Double
      return PageDetection(qrPayload, markerCorners, missingMarkerIds, blurScore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      qrPayload,
      markerCorners,
      missingMarkerIds,
      blurScore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PageDetection
    return ScanApiPigeonUtils.deepEquals(this.qrPayload, other.qrPayload) && ScanApiPigeonUtils.deepEquals(this.markerCorners, other.markerCorners) && ScanApiPigeonUtils.deepEquals(this.missingMarkerIds, other.missingMarkerIds) && ScanApiPigeonUtils.deepEquals(this.blurScore, other.blurScore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.qrPayload)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.markerCorners)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.missingMarkerIds)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.blurScore)
    return result
  }
  override fun toString(): String {
    return "PageDetection(qrPayload=$qrPayload, markerCorners=$markerCorners, missingMarkerIds=$missingMarkerIds, blurScore=$blurScore)"
  }
}

/**
 * One crop cut from the warped page.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class RegionCrop (
  /**
   * `region_id` from the layout JSON. The final-answer box of a `lines`
   * region comes back as its own crop with the id `<region_id>_final`.
   */
  val regionId: String,
  /**
   * WebP (quality 80), at most 768 px on the long side (DESIGN §21.9), in
   * the app cache directory.
   */
  val imagePath: String,
  /**
   * `ink_ratio` (DESIGN §9.4, §11.8): share of the rect (without its printed
   * border, ruling and line-number gutter) that lies within 2 mm of
   * handwriting, specks ignored (0..1). Blank reads 0, one written digit in
   * a box about 0.05; above 0.02 means something is written. 0 for `mcq`.
   */
  val inkRatio: Double,
  /**
   * `mcq` only: option -> share of dark pixels inside 70% of the bubble
   * radius (Otsu threshold), e.g. {"A": 0.04, "B": 0.83}.
   */
  val bubbleFill: Map<String, Double>? = null,
  /**
   * Numeric boxes only: 32 x 128 grayscale bytes (row-major, paper = 255,
   * ink dark) prepared as in ml/train/preprocess.py (tight crop + fit to
   * canvas); the Dart side normalises and runs the digit reader.
   */
  val cnnInput: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): RegionCrop {
      val regionId = pigeonVar_list[0] as String
      val imagePath = pigeonVar_list[1] as String
      val inkRatio = pigeonVar_list[2] as Double
      val bubbleFill = pigeonVar_list[3] as Map<String, Double>?
      val cnnInput = pigeonVar_list[4] as ByteArray?
      return RegionCrop(regionId, imagePath, inkRatio, bubbleFill, cnnInput)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      regionId,
      imagePath,
      inkRatio,
      bubbleFill,
      cnnInput,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as RegionCrop
    return ScanApiPigeonUtils.deepEquals(this.regionId, other.regionId) && ScanApiPigeonUtils.deepEquals(this.imagePath, other.imagePath) && ScanApiPigeonUtils.deepEquals(this.inkRatio, other.inkRatio) && ScanApiPigeonUtils.deepEquals(this.bubbleFill, other.bubbleFill) && ScanApiPigeonUtils.deepEquals(this.cnnInput, other.cnnInput)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.regionId)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.imagePath)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.inkRatio)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.bubbleFill)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.cnnInput)
    return result
  }
  override fun toString(): String {
    return "RegionCrop(regionId=$regionId, imagePath=$imagePath, inkRatio=$inkRatio, bubbleFill=$bubbleFill, cnnInput=${cnnInput?.contentToString()})"
  }
}

/**
 * Everything cut from one page.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PageCrops (
  /** The marker frame warped flat, WebP about 1600 px on the long side. */
  val warpedPagePath: String,
  val regions: List<RegionCrop>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PageCrops {
      val warpedPagePath = pigeonVar_list[0] as String
      val regions = pigeonVar_list[1] as List<RegionCrop>
      return PageCrops(warpedPagePath, regions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      warpedPagePath,
      regions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PageCrops
    return ScanApiPigeonUtils.deepEquals(this.warpedPagePath, other.warpedPagePath) && ScanApiPigeonUtils.deepEquals(this.regions, other.regions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.warpedPagePath)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.regions)
    return result
  }
  override fun toString(): String {
    return "PageCrops(warpedPagePath=$warpedPagePath, regions=$regions)"
  }
}

/**
 * What one downscaled camera frame shows (DESIGN §22.10): enough to decide
 * whether to take the full photo, nothing is warped or cropped.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class FrameDetection (
  /** Number of the corner markers id 0..3 found (0..4). */
  val markersFound: Long,
  /** Raw QR text, or null when no QR could be read. */
  val qrPayload: String? = null,
  /**
   * Variance of the Laplacian of the marker frame warped at the frame's
   * own resolution (0 when fewer than four markers were found).
   */
  val blurScore: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FrameDetection {
      val markersFound = pigeonVar_list[0] as Long
      val qrPayload = pigeonVar_list[1] as String?
      val blurScore = pigeonVar_list[2] as Double
      return FrameDetection(markersFound, qrPayload, blurScore)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      markersFound,
      qrPayload,
      blurScore,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FrameDetection
    return ScanApiPigeonUtils.deepEquals(this.markersFound, other.markersFound) && ScanApiPigeonUtils.deepEquals(this.qrPayload, other.qrPayload) && ScanApiPigeonUtils.deepEquals(this.blurScore, other.blurScore)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.markersFound)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.qrPayload)
    result = 31 * result + ScanApiPigeonUtils.deepHash(this.blurScore)
    return result
  }
  override fun toString(): String {
    return "FrameDetection(markersFound=$markersFound, qrPayload=$qrPayload, blurScore=$blurScore)"
  }
}
private open class ScanApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PageDetection.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          RegionCrop.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PageCrops.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FrameDetection.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PageDetection -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is RegionCrop -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PageCrops -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is FrameDetection -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ScanPipelineApi {
  /** Finds the markers, reads the QR and measures blur on a full photo. */
  suspend fun detectPage(imagePath: String): PageDetection
  /**
   * Warps the marker frame to ~200 DPI and crops every region of
   * [layoutJson] (one page of the layout JSON, DESIGN §5.3).
   */
  suspend fun cropPage(imagePath: String, detection: PageDetection, layoutJson: String): PageCrops
  /**
   * Exam answer sheets (DESIGN §22.9): warps the marker frame like
   * [cropPage] and measures every bubble of the `version_bubbles`,
   * `omr_row` and `digit_block` regions of [layoutJson] (one page, sheet
   * `exam`). Returns JSON: {warped_page_path, blur_score, baseline,
   * version_fill, rows, digits}, fills after the page baseline.
   */
  suspend fun readAnswerSheet(imagePath: String, detection: PageDetection, layoutJson: String): String
  /**
   * Markers, QR and blur of one camera frame (the Y plane of a YUV_420
   * image, [bytesPerRow] per row) for continuous scanning (§22.10).
   */
  suspend fun detectFrame(yPlane: ByteArray, width: Long, height: Long, bytesPerRow: Long, rotation: Long): FrameDetection

  companion object {
    /** The codec used by ScanPipelineApi. */
    val codec: MessageCodec<Any?> by lazy {
      ScanApiPigeonCodec()
    }
    /** Sets up an instance of `ScanPipelineApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ScanPipelineApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eduvision.ScanPipelineApi.detectPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imagePathArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.detectPage(imagePathArg))
              } catch (exception: Throwable) {
                ScanApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eduvision.ScanPipelineApi.cropPage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imagePathArg = args[0] as String
            val detectionArg = args[1] as PageDetection
            val layoutJsonArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.cropPage(imagePathArg, detectionArg, layoutJsonArg))
              } catch (exception: Throwable) {
                ScanApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eduvision.ScanPipelineApi.readAnswerSheet$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val imagePathArg = args[0] as String
            val detectionArg = args[1] as PageDetection
            val layoutJsonArg = args[2] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.readAnswerSheet(imagePathArg, detectionArg, layoutJsonArg))
              } catch (exception: Throwable) {
                ScanApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.eduvision.ScanPipelineApi.detectFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val yPlaneArg = args[0] as ByteArray
            val widthArg = args[1] as Long
            val heightArg = args[2] as Long
            val bytesPerRowArg = args[3] as Long
            val rotationArg = args[4] as Long
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.detectFrame(yPlaneArg, widthArg, heightArg, bytesPerRowArg, rotationArg))
              } catch (exception: Throwable) {
                ScanApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
