<?php

namespace Tests\Unit\Grading;

use App\Domain\Grading\AnswerMatcher;
use App\Domain\Grading\FuzzyGrader;
use App\Domain\Grading\GradeResult;
use App\Domain\Grading\PrioritySignals;
use App\Domain\Grading\ReviewPriority;
use App\Domain\Grading\ScoreRounding;
use PHPUnit\Framework\TestCase;

/**
 * The PHP port against the Python reference (ml/fuzzy, DESIGN §11.9): every
 * case in tests/fixtures/fuzzy_golden.json, generated by fuzzy_golden.py in
 * the same folder, must come out the same here.
 */
class FuzzyCrossCheckTest extends TestCase
{
    private const DELTA = 1e-12;

    /** @var array<string, mixed>|null */
    private static ?array $golden = null;

    /**
     * @return array<string, mixed>
     */
    private static function golden(): array
    {
        return self::$golden ??= json_decode(
            (string) file_get_contents(dirname(__DIR__, 2).'/fixtures/fuzzy_golden.json'),
            true,
            flags: JSON_THROW_ON_ERROR,
        );
    }

    public function test_show_work_matches_the_reference(): void
    {
        $cases = self::golden()['show_work'];
        $this->assertGreaterThan(100, count($cases));
        foreach ($cases as $case) {
            $result = FuzzyGrader::showWork($case['F'], $case['S'], $case['strictness']);
            $this->assertSameResult($case, $result, "show_work F={$case['F']} S={$case['S']} {$case['strictness']}");
            $this->assertSame((float) $case['ai_score_5'], $result->score(5));
        }
    }

    public function test_short_matches_the_reference(): void
    {
        foreach (self::golden()['short'] as $case) {
            $this->assertSameResult($case, FuzzyGrader::short($case['M'], $case['strictness']), "short M={$case['M']} {$case['strictness']}");
        }
    }

    public function test_open_matches_the_reference(): void
    {
        foreach (self::golden()['open'] as $case) {
            $this->assertSameResult($case, FuzzyGrader::open($case['K'], $case['R'], $case['strictness']), "open K={$case['K']} R={$case['R']} {$case['strictness']}");
        }
    }

    public function test_review_priority_matches_the_reference(): void
    {
        $cases = self::golden()['review_priority'];
        $this->assertCount(216, $cases);
        foreach ($cases as $case) {
            $result = ReviewPriority::evaluate($case['D'], $case['L'], $case['B']);
            $label = "priority D={$case['D']} L={$case['L']} B={$case['B']}";
            $this->assertEqualsWithDelta($case['p'], $result->p, self::DELTA, $label);
            $this->assertSame($case['band'], $result->band, $label);
            $this->assertEqualsWithDelta($case['weights'], $result->trace->weights(), self::DELTA, $label);
        }
    }

    public function test_answer_matching_matches_the_reference(): void
    {
        $m = self::golden()['matching'];
        foreach ($m['short_match'] as $case) {
            $this->assertEqualsWithDelta(
                $case['M'],
                AnswerMatcher::shortMatch($case['answer'], $case['answer_key'], $case['match_mode'], $case['key_match']),
                self::DELTA,
                'short_match '.json_encode($case, JSON_UNESCAPED_UNICODE),
            );
        }
        foreach ($m['similarity'] as $case) {
            $this->assertEqualsWithDelta($case['sim'], AnswerMatcher::similarity($case['a'], $case['b']), self::DELTA, "sim {$case['a']} / {$case['b']}");
        }
        foreach ($m['parse_number'] as $case) {
            $this->assertSame($case['value'] === null ? null : (float) $case['value'], AnswerMatcher::parseNumber($case['text']), "parse '{$case['text']}'");
        }
        foreach ($m['numeric_match'] as $case) {
            $this->assertEqualsWithDelta($case['M'], AnswerMatcher::numericMatch($case['answer'], $case['key'], $case['abs_tol']), self::DELTA);
        }
        foreach ($m['final_answer_value'] as $case) {
            $this->assertEqualsWithDelta($case['F'], AnswerMatcher::finalAnswerValue($case['match'], $case['text'], $case['final_key']), self::DELTA);
        }
    }

    public function test_priority_signals_match_the_reference(): void
    {
        $s = self::golden()['signals'];
        foreach ($s['boundary_closeness'] as $case) {
            $this->assertEqualsWithDelta($case['B'], ReviewPriority::boundaryCloseness($case['u']), self::DELTA, "B u={$case['u']}");
        }
        foreach ($s['illegibility'] as $case) {
            $this->assertEqualsWithDelta($case['L'], PrioritySignals::illegibility($case['legibility'], $case['text']), self::DELTA, "L '{$case['text']}'");
        }
        foreach ($s['unknown_ratio'] as $case) {
            $this->assertEqualsWithDelta($case['ratio'], PrioritySignals::unknownRatio($case['text']), self::DELTA);
        }
        foreach ($s['reader_disagreement'] as $case) {
            $this->assertSame((float) $case['D'], PrioritySignals::readerDisagreement($case['cnn'], $case['gemini'], $case['numeric']), json_encode($case));
        }
        foreach ($s['blank_disagreement'] as $case) {
            $this->assertSame((float) $case['D'], PrioritySignals::blankDisagreement($case['blank'], $case['ink_ratio']));
        }
    }

    public function test_open_inputs_and_rounding_match_the_reference(): void
    {
        foreach (self::golden()['open_inputs'] as $case) {
            [$k, $r] = FuzzyGrader::openInputs($case['criteria']);
            $this->assertEqualsWithDelta($case['K'], $k, self::DELTA);
            $this->assertEqualsWithDelta($case['R'], $r, self::DELTA);
        }
        foreach (self::golden()['rounding'] as $case) {
            $this->assertSame(
                (float) $case['ai_score'],
                ScoreRounding::score($case['score_ratio'], $case['max_points'], $case['step']),
                "round_half {$case['score_ratio']} x {$case['max_points']} step {$case['step']}",
            );
        }
    }

    /**
     * @param  array<string, mixed>  $case
     */
    private function assertSameResult(array $case, GradeResult $result, string $label): void
    {
        $this->assertSame($case['grading_state'], $result->state, $label);
        $this->assertEqualsWithDelta($case['score_ratio'], $result->scoreRatio, self::DELTA, $label);
        $this->assertEqualsWithDelta($case['u'], $result->u, self::DELTA, $label);
        $this->assertSame($case['understanding'], $result->understanding, $label);
        $this->assertEqualsWithDelta($case['weights'], $result->trace->weights(), self::DELTA, $label);
        $this->assertEqualsWithDelta($case['weight_sum'], $result->trace->weightSum, self::DELTA, $label);
    }
}
