<?php

namespace App\Domain\Worksheets;

use RuntimeException;

/**
 * The four ArUco corner markers generated by ml/tools/gen_aruco.py into
 * backend/resources/worksheet/aruco (DESIGN §5.2). The PNG includes a white
 * quiet zone, so it is larger than the marker; its centre goes on the frame
 * corner (manifest.json `print.note`).
 */
final class ArucoMarkers
{
    private const CORNERS = [
        'top_left' => [WorksheetGeometry::FRAME_X, WorksheetGeometry::FRAME_Y],
        'top_right' => [WorksheetGeometry::FRAME_X + WorksheetGeometry::FRAME_W, WorksheetGeometry::FRAME_Y],
        'bottom_right' => [WorksheetGeometry::FRAME_X + WorksheetGeometry::FRAME_W, WorksheetGeometry::FRAME_Y + WorksheetGeometry::FRAME_H],
        'bottom_left' => [WorksheetGeometry::FRAME_X, WorksheetGeometry::FRAME_Y + WorksheetGeometry::FRAME_H],
    ];

    /**
     * @param  list<array{id: int, file: string, cx: float, cy: float}>  $markers
     */
    private function __construct(
        public readonly string $dictionary,
        public readonly float $markerSizeMm,
        public readonly float $imageSizeMm,
        public readonly array $markers,
    ) {}

    public static function load(?string $dir = null): self
    {
        $dir ??= resource_path('worksheet/aruco');
        $manifest = json_decode((string) @file_get_contents($dir.'/manifest.json'), true);
        if (! is_array($manifest) || ! isset($manifest['dictionary'], $manifest['print']['marker_size_mm'], $manifest['print']['image_size_mm'], $manifest['markers'])) {
            throw new RuntimeException("ArUco manifest missing or invalid in {$dir}");
        }

        $markers = [];
        foreach ($manifest['markers'] as $marker) {
            $corner = self::CORNERS[$marker['corner'] ?? ''] ?? null;
            $file = $dir.'/'.basename((string) ($marker['file'] ?? ''));
            if ($corner === null || ! is_file($file)) {
                throw new RuntimeException('ArUco marker entry is invalid: '.json_encode($marker));
            }
            $markers[] = ['id' => (int) $marker['id'], 'file' => $file, 'cx' => $corner[0], 'cy' => $corner[1]];
        }
        usort($markers, fn (array $a, array $b) => $a['id'] <=> $b['id']);

        if (array_column($markers, 'id') !== [0, 1, 2, 3]) {
            throw new RuntimeException('The worksheet needs ArUco markers 0–3 exactly once.');
        }

        return new self(
            (string) $manifest['dictionary'],
            (float) $manifest['print']['marker_size_mm'],
            (float) $manifest['print']['image_size_mm'],
            $markers,
        );
    }

    /** @return array{dictionary: string, ids: list<int>, size_mm: float|int} */
    public function layoutJson(): array
    {
        $size = $this->markerSizeMm;

        return [
            'dictionary' => $this->dictionary,
            'ids' => array_column($this->markers, 'id'),
            'size_mm' => floor($size) === $size ? (int) $size : $size,
        ];
    }
}
