// Autogenerated from Pigeon (v29.0.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Result of looking at a full photo of a worksheet page.
class PageDetection {
  PageDetection({
    this.qrPayload,
    required this.markerCorners,
    required this.missingMarkerIds,
    required this.blurScore,
  });

  /// Raw QR text, or null when no QR could be read.
  String? qrPayload;

  /// Centres of the ArUco markers id 0..3 (top-left, top-right,
  /// bottom-right, bottom-left) in pixel coordinates of the photo as decoded
  /// with its EXIF orientation applied: [x0, y0, x1, y1, x2, y2, x3, y3].
  /// Both values of a marker that was not found are null.
  List<double?> markerCorners;

  /// Ids (0..3) of the markers that were not found, so the UI can say which
  /// corner is out of the frame.
  List<int> missingMarkerIds;

  /// Variance of the Laplacian. Measured on the marker frame warped to
  /// 200 DPI when all four markers were found, otherwise on the downscaled
  /// photo. Higher is sharper.
  double blurScore;

  List<Object?> _toList() {
    return <Object?>[qrPayload, markerCorners, missingMarkerIds, blurScore];
  }

  Object encode() {
    return _toList();
  }

  static PageDetection decode(Object result) {
    result as List<Object?>;
    return PageDetection(
      qrPayload: result[0] as String?,
      markerCorners: (result[1]! as List<Object?>).cast<double?>(),
      missingMarkerIds: (result[2]! as List<Object?>).cast<int>(),
      blurScore: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageDetection || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(qrPayload, other.qrPayload) &&
        _deepEquals(markerCorners, other.markerCorners) &&
        _deepEquals(missingMarkerIds, other.missingMarkerIds) &&
        _deepEquals(blurScore, other.blurScore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageDetection(qrPayload: $qrPayload, markerCorners: $markerCorners, missingMarkerIds: $missingMarkerIds, blurScore: $blurScore)';
  }
}

/// One crop cut from the warped page.
class RegionCrop {
  RegionCrop({
    required this.regionId,
    required this.imagePath,
    required this.inkRatio,
    this.bubbleFill,
    this.cnnInput,
  });

  /// `region_id` from the layout JSON. The final-answer box of a `lines`
  /// region comes back as its own crop with the id `<region_id>_final`.
  String regionId;

  /// WebP (quality 80), at most 768 px on the long side (DESIGN §21.9), in
  /// the app cache directory.
  String imagePath;

  /// `ink_ratio` (DESIGN §9.4, §11.8): share of the rect (without its printed
  /// border, ruling and line-number gutter) that lies within 2 mm of
  /// handwriting, specks ignored (0..1). Blank reads 0, one written digit in
  /// a box about 0.05; above 0.02 means something is written. 0 for `mcq`.
  double inkRatio;

  /// `mcq` only: option -> share of dark pixels inside 70% of the bubble
  /// radius (Otsu threshold), e.g. {"A": 0.04, "B": 0.83}.
  Map<String, double>? bubbleFill;

  /// Numeric boxes only: 32 x 128 grayscale bytes (row-major, paper = 255,
  /// ink dark) prepared as in ml/train/preprocess.py (tight crop + fit to
  /// canvas); the Dart side normalises and runs the digit reader.
  Uint8List? cnnInput;

  List<Object?> _toList() {
    return <Object?>[regionId, imagePath, inkRatio, bubbleFill, cnnInput];
  }

  Object encode() {
    return _toList();
  }

  static RegionCrop decode(Object result) {
    result as List<Object?>;
    return RegionCrop(
      regionId: result[0]! as String,
      imagePath: result[1]! as String,
      inkRatio: result[2]! as double,
      bubbleFill: (result[3] as Map<Object?, Object?>?)?.cast<String, double>(),
      cnnInput: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! RegionCrop || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(regionId, other.regionId) &&
        _deepEquals(imagePath, other.imagePath) &&
        _deepEquals(inkRatio, other.inkRatio) &&
        _deepEquals(bubbleFill, other.bubbleFill) &&
        _deepEquals(cnnInput, other.cnnInput);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'RegionCrop(regionId: $regionId, imagePath: $imagePath, inkRatio: $inkRatio, bubbleFill: $bubbleFill, cnnInput: $cnnInput)';
  }
}

/// Everything cut from one page.
class PageCrops {
  PageCrops({required this.warpedPagePath, required this.regions});

  /// The marker frame warped flat, WebP about 1600 px on the long side.
  String warpedPagePath;

  List<RegionCrop> regions;

  List<Object?> _toList() {
    return <Object?>[warpedPagePath, regions];
  }

  Object encode() {
    return _toList();
  }

  static PageCrops decode(Object result) {
    result as List<Object?>;
    return PageCrops(
      warpedPagePath: result[0]! as String,
      regions: (result[1]! as List<Object?>).cast<RegionCrop>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PageCrops || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(warpedPagePath, other.warpedPagePath) &&
        _deepEquals(regions, other.regions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PageCrops(warpedPagePath: $warpedPagePath, regions: $regions)';
  }
}

/// What one downscaled camera frame shows (DESIGN §22.10): enough to decide
/// whether to take the full photo, nothing is warped or cropped.
class FrameDetection {
  FrameDetection({
    required this.markersFound,
    this.qrPayload,
    required this.blurScore,
  });

  /// Number of the corner markers id 0..3 found (0..4).
  int markersFound;

  /// Raw QR text, or null when no QR could be read.
  String? qrPayload;

  /// Variance of the Laplacian of the marker frame warped at the frame's
  /// own resolution (0 when fewer than four markers were found).
  double blurScore;

  List<Object?> _toList() {
    return <Object?>[markersFound, qrPayload, blurScore];
  }

  Object encode() {
    return _toList();
  }

  static FrameDetection decode(Object result) {
    result as List<Object?>;
    return FrameDetection(
      markersFound: result[0]! as int,
      qrPayload: result[1] as String?,
      blurScore: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FrameDetection || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(markersFound, other.markersFound) &&
        _deepEquals(qrPayload, other.qrPayload) &&
        _deepEquals(blurScore, other.blurScore);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FrameDetection(markersFound: $markersFound, qrPayload: $qrPayload, blurScore: $blurScore)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is PageDetection) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is RegionCrop) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PageCrops) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is FrameDetection) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return PageDetection.decode(readValue(buffer)!);
      case 130:
        return RegionCrop.decode(readValue(buffer)!);
      case 131:
        return PageCrops.decode(readValue(buffer)!);
      case 132:
        return FrameDetection.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ScanPipelineApi {
  /// Constructor for [ScanPipelineApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ScanPipelineApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Finds the markers, reads the QR and measures blur on a full photo.
  Future<PageDetection> detectPage(String imagePath) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.eduvision.ScanPipelineApi.detectPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[imagePath],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PageDetection;
  }

  /// Warps the marker frame to ~200 DPI and crops every region of
  /// [layoutJson] (one page of the layout JSON, DESIGN §5.3).
  Future<PageCrops> cropPage(
    String imagePath,
    PageDetection detection,
    String layoutJson,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.eduvision.ScanPipelineApi.cropPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[imagePath, detection, layoutJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PageCrops;
  }

  /// Exam answer sheets (DESIGN §22.9): warps the marker frame like
  /// [cropPage] and measures every bubble of the `version_bubbles`,
  /// `omr_row` and `digit_block` regions of [layoutJson] (one page, sheet
  /// `exam`). Returns JSON: {warped_page_path, blur_score, baseline,
  /// version_fill, rows, digits}, fills after the page baseline.
  Future<String> readAnswerSheet(
    String imagePath,
    PageDetection detection,
    String layoutJson,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.eduvision.ScanPipelineApi.readAnswerSheet$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[imagePath, detection, layoutJson],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Markers, QR and blur of one camera frame (the Y plane of a YUV_420
  /// image, [bytesPerRow] per row) for continuous scanning (§22.10).
  Future<FrameDetection> detectFrame(
    Uint8List yPlane,
    int width,
    int height,
    int bytesPerRow,
    int rotation,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.eduvision.ScanPipelineApi.detectFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[yPlane, width, height, bytesPerRow, rotation],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as FrameDetection;
  }
}

/// Pages of a teacher's exam file for cropping its figures (DESIGN §22.4):
/// the server cannot render a PDF or decode HEIC, so the phone does and
/// uploads the page (`POST /exams/{id}/page-images`).
class DocumentPageApi {
  /// Constructor for [DocumentPageApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DocumentPageApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Renders page [pageNo] (1-based) of the PDF at [path] with
  /// `PdfRenderer`, or decodes the photo at [path] (HEIC/HEIF, JPEG, PNG,
  /// WebP; [pageNo] must be 1), on white, scaled so the long side is at most
  /// [maxLongSide] px. Writes a JPEG (quality 90) to the app cache and
  /// returns its path. Errors: `document_unreadable`, `page_out_of_range`,
  /// `unsupported` (HEIC before Android 9), `storage_failed`.
  Future<String> renderDocumentPage(
    String path,
    String mimeType,
    int pageNo,
    int maxLongSide,
  ) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.eduvision.DocumentPageApi.renderDocumentPage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[path, mimeType, pageNo, maxLongSide],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }
}
